on:
  issues:
    types:
      - assigned

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run start
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
